name: Lint

on: [push, pull_request]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Backend code formatting check (Black)
        uses: psf/black@stable

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Display Prettier version
        run: npx prettier --version
        working-directory: ./frontend

      - name: Display contents
        run: cat .prettierrc .prettierignore
        working-directory: ./frontend

      - name: Frontend code formatting check (Prettier)
        run: npm run format:check
        working-directory: ./frontend
